CXXFLAGS = -g -c -Istb -O6 -Ofast  -funroll-loops -funroll-all-loops -fomit-frame-pointer -fno-exceptions -fno-rtti -ffast-math -mtune=i386 -march=i386 -fpermissive

LDFLAGS = -lemu

CXX = i586-pc-msdosdjgpp-g++

OBJS = Main.o Game.o LoadImageVGA.o NativeBitmap.o MusicDOS.o VGARenderer.o

TARGET = vianavga.exe

$(TARGET):	$(OBJS)
	$(CXX) -o $(TARGET) $(OBJS) $(LDFLAGS)

all:	$(TARGET)

clean:
	rm -f $(OBJS) $(TARGET)
	rm *~
